### ISSUE TITLE
Help getting started!

### ISSUE THREAD

**Issue by grusad** [stg-tud/rxrefactoring-code#5]
We are currently in the middle of our bachelor thesis, and would like to use this software in our project. Been trying to get the tool up and running without any success. You refer to the documentation section at the website, but either I'm completely blind or its missing.

So, how do we use this awesome tool? And can it be used without eclipse? :)

Stay healthy,
Gillberg and Holst

**Comment by mkoee** [comment]
In the current state, the tool can not be used without Eclipse. To use it, download the [Eclipse for Eclipse commiters](https://www.eclipse.org/downloads/packages/release/2020-03/r/eclipse-ide-eclipse-committers) IDE and load the code from the Git repo. You can start the plugin by selecting "Run as > Eclipse Application" in Eclipse.

Best,
Mirko

**Comment by grusad** [comment]
Wow, finally! We spent days trying to get this up and running and was about to abandoned it all! Thanks!
